# 工具链设置
set(GCC_SUFFIX riscv-none-embed-)
find_path(_TOOLCHAIN ${GCC_SUFFIX}gcc.exe)
set(TOOLPATH "${_TOOLCHAIN}")

if (WIN32)
	MESSAGE(STATUS "Now is windows!")
    set(CMAKE_C_COMPILER ${TOOLPATH}/${GCC_SUFFIX}gcc.exe)
    set(CMAKE_CXX_COMPILER ${TOOLPATH}/${GCC_SUFFIX}g++.exe)
    set(CMAKE_ASM_COMPILER ${TOOLPATH}/${GCC_SUFFIX}gcc.exe)
    set(CMAKE_AR ${TOOLPATH}/${GCC_SUFFIX}ar.exe)
    set(CMAKE_OBJCOPY ${TOOLPATH}/${GCC_SUFFIX}objcopy.exe)
    set(CMAKE_OBJDUMP ${TOOLPATH}/${GCC_SUFFIX}objdump.exe)
    set(SIZE ${TOOLPATH}/${GCC_SUFFIX}size.exe)
else ()   # For Unix/Linux
	MESSAGE(STATUS "Now is not windows!")
    set(CMAKE_C_COMPILER ${TOOLPATH}/${GCC_SUFFIX}gcc)
    set(CMAKE_CXX_COMPILER ${TOOLPATH}/${GCC_SUFFIX}g++)
    set(CMAKE_ASM_COMPILER ${TOOLPATH}/${GCC_SUFFIX}gcc)
    set(CMAKE_AR ${TOOLPATH}/${GCC_SUFFIX}ar)
    set(CMAKE_OBJCOPY ${TOOLPATH}/${GCC_SUFFIX}objcopy)
    set(CMAKE_OBJDUMP ${TOOLPATH}/${GCC_SUFFIX}objdump)
    set(SIZE ${TOOLPATH}/${GCC_SUFFIX}size)
endif ()
