# generate_flash.cmake
# 此脚本由主 CMakeLists.txt 在 POST_BUILD 阶段调用，仅负责写入 .bat 文件

# 直接写入完整的 bat 脚本，不在 CMake 中拼接复杂命令
file(WRITE "${BUILD_DIR}/flash.bat"
    "@echo off\n"
    "REM Auto-generated by CMake POST_BUILD event\n"
    "REM OpenOCD Flash Script for ${PROJECT_NAME}\n\n"
    
    "REM Step 1: Erase Flash\n"
    "\"${OPENOCD_EXE}\" -f \"${OPENOCD_CFG}\" "
    "-c \"init\" -c \"halt\" "
    "-c \"flash erase_sector 0 0 last\" "
    "-c \"exit\"\n\n"
    
    "REM Step 2: Program and Verify\n"
    "\"${OPENOCD_EXE}\" -f \"${OPENOCD_CFG}\" "
    "-c \"init\" -c \"halt\" "
    "-c \"program \\\"${HEX_FILE}\\\" verify\" "
    "-c \"exit\"\n\n"
    
    "REM Step 3: Reset MCU\n"
    "\"${OPENOCD_EXE}\" -f \"${OPENOCD_CFG}\" "
    "-c \"init\" -c \"halt\" "
    "-c \"wlink_reset_resume\" "
    "-c \"exit\"\n"
)

message(STATUS "Generated flash.bat at ${BUILD_DIR}/flash.bat")

